services:
  nextjs:
    build:
      context: .
      target: builder
    container_name: dev_jeremydan
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
